### ISSUE TITLE
where is the paper?

### ISSUE THREAD

**Issue by vounteer** [hiennguyen9874/person-attribute-recognition#1]
Hello,Do you have a corresponding paper？

**Comment by hiennguyen9874** [comment]
I mainly refer from: [A Strong Baseline of Pedestrian Attribute Recognition](https://arxiv.org/pdf/2005.11909.pdf), [OSNet](https://arxiv.org/pdf/1905.00953.pdf) and [fast reid](https://arxiv.org/pdf/2006.02631.pdf). My project still in progress and the document has not yet been written. I will do it soon. Sorry about my English.
