### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'base/config.json'

### ISSUE THREAD

**Issue by xagpx** [hiennguyen9874/person-attribute-recognition#7]
FileNotFoundError: [Errno 2] No such file or directory: 'base/config.json'

**Comment by hiennguyen9874** [comment]
it was renamed config/base_epoch.yml. You can using config/baselineline_peta.yml for peta dataset or config/baseline_pa100k.yml for pa100k dataset. Thanks
